<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $products = [
            [
                'id' => '1',
                'name' => 'Sweater Rajut Pink Oversize',
                'price' => 85000,
                'original_price' => 320000,
                'description' => 'Sweater rajut premium warna pink. Bahan lembut dan nyaman dipakai. Kondisi sangat terawat.',
                'condition' => 'Sangat Baik',
                'brand' => 'Unbranded',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '300g',
                'material' => 'Rajut Akrilik',
                'tags' => ['sweater', 'rajut', 'pink'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-2-D1V8gELu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['M', 'L']]],
            ],
            [
                'id' => '2',
                'name' => 'Crop Top Stripe Monochrome',
                'price' => 65000,
                'original_price' => 220000,
                'description' => 'Crop top motif stripe hitam-putih trendi. Bahan stretch nyaman.',
                'condition' => 'Baik',
                'brand' => 'H&M',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '200g',
                'material' => 'Cotton Stretch',
                'tags' => ['crop top', 'stripe'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-3-C2haDO2D.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['S', 'M']]],
            ],
            [
                'id' => '3',
                'name' => 'Polo Crop Navy Premium',
                'price' => 75000,
                'original_price' => 280000,
                'description' => 'Polo shirt crop warna navy elegan. Bahan berkualitas, terasa adem.',
                'condition' => 'Sangat Baik',
                'brand' => 'Uniqlo',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '250g',
                'material' => 'Pique Cotton',
                'tags' => ['polo', 'crop', 'navy'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-4-C6tSW0GE.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['M']]],
            ],
            [
                'id' => '4',
                'name' => 'Blouse Ruffle Putih Elegan',
                'price' => 110000,
                'original_price' => 430000,
                'description' => 'Blouse detail ruffle feminin dan elegan. Warna putih bersih, bahan ringan.',
                'condition' => 'Sangat Baik',
                'brand' => 'Zara',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '220g',
                'material' => 'Chiffon',
                'tags' => ['blouse', 'ruffle', 'elegan'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-5-QEo8_1xu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['S', 'M']]],
            ],
            [
                'id' => '5',
                'name' => 'Casual Blazer Cream',
                'price' => 145000,
                'original_price' => 580000,
                'description' => 'Blazer kasual warna cream netral. Sangat cocok untuk acara semi-formal maupun formal.',
                'condition' => 'Sangat Baik',
                'brand' => 'Mango',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '450g',
                'material' => 'Polyester Blend',
                'tags' => ['blazer', 'cream', 'casual'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-2-D1V8gELu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['M', 'L']]],
            ],
            [
                'id' => '6',
                'name' => 'Denim Jacket Vintage Blue',
                'price' => 175000,
                'original_price' => 690000,
                'description' => 'Jaket denim tebal gaya vintage. Warna biru pudar alami, stylish untuk layering.',
                'condition' => 'Baik',
                'brand' => 'Levi\'s',
                'category' => 'Fashion Pria',
                'stock' => 1,
                'weight' => '600g',
                'material' => '100% Cotton Denim',
                'tags' => ['jacket', 'denim', 'vintage'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-3-C2haDO2D.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['L', 'XL']]],
            ],
            [
                'id' => '7',
                'name' => 'Pleated Skirt Olive Green',
                'price' => 90000,
                'original_price' => 350000,
                'description' => 'Rok plisket warna hijau olive yang estetik. Karet pinggang nyaman stretch.',
                'condition' => 'Sangat Baik',
                'brand' => 'Unbranded',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '280g',
                'material' => 'Premium Pleated Crepe',
                'tags' => ['skirt', 'pleated', 'olive'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-4-C6tSW0GE.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['All Size']]],
            ],
            [
                'id' => '8',
                'name' => 'Floral Summer Dress',
                'price' => 125000,
                'original_price' => 450000,
                'description' => 'Dress motif bunga-bunga cantik untuk musim panas. Bahan adem dan jatuh di badan.',
                'condition' => 'Sangat Baik',
                'brand' => 'Pull & Bear',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '240g',
                'material' => 'Rayon Viscose',
                'tags' => ['dress', 'floral', 'summer'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-5-QEo8_1xu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['S', 'M']]],
            ],
            [
                'id' => '9',
                'name' => 'Black Linen Trousers',
                'price' => 105000,
                'original_price' => 399000,
                'description' => 'Celana panjang bahan linen warna hitam. Sejuk dipakai seharian, gaya kasual santai.',
                'condition' => 'Baik',
                'brand' => 'Uniqlo',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '320g',
                'material' => 'Linen Blend',
                'tags' => ['trousers', 'linen', 'black'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-2-D1V8gELu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['M', 'L']]],
            ],
            [
                'id' => '10',
                'name' => 'Knit Cardigan Soft Yellow',
                'price' => 95000,
                'original_price' => 380000,
                'description' => 'Cardigan rajut warna kuning pastel lembut. Lucu untuk outfit OOTD harian.',
                'condition' => 'Sangat Baik',
                'brand' => 'Cotton On',
                'category' => 'Fashion Wanita',
                'stock' => 1,
                'weight' => '290g',
                'material' => 'Acrylic Knit',
                'tags' => ['cardigan', 'knit', 'yellow'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-3-C2haDO2D.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['M']]],
            ],
            [
                'id' => '11',
                'name' => 'Handbag Leather Coffee',
                'price' => 220000,
                'original_price' => 890000,
                'description' => 'Tas tangan bahan kulit imitasi warna cokelat kopi. Muat banyak barang dan terlihat vintage.',
                'condition' => 'Sangat Baik',
                'brand' => 'Charles & Keith',
                'category' => 'Tas',
                'stock' => 1,
                'weight' => '500g',
                'material' => 'PU Leather',
                'tags' => ['handbag', 'leather', 'brown'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-4-C6tSW0GE.png'],
                'variants' => [['name' => 'Warna', 'options' => ['Coffee Brown']]],
            ],
            [
                'id' => '12',
                'name' => 'Canvas Sneaker White',
                'price' => 180000,
                'original_price' => 750000,
                'description' => 'Sepatu sneakers kanvas warna putih bersih. Klasik dan selalu cocok dengan segala gaya.',
                'condition' => 'Baik',
                'brand' => 'Converse',
                'category' => 'Sepatu',
                'stock' => 1,
                'weight' => '700g',
                'material' => 'Canvas & Rubber',
                'tags' => ['sneaker', 'canvas', 'white'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-5-QEo8_1xu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['38', '39', '40']]],
            ],
            [
                'id' => '13',
                'name' => 'Sunglasses Retro Brown',
                'price' => 45000,
                'original_price' => 180000,
                'description' => 'Kacamata hitam frame cokelat retro bergaya klasik tahun 90-an.',
                'condition' => 'Sangat Baik',
                'brand' => 'Unbranded',
                'category' => 'Aksesoris',
                'stock' => 1,
                'weight' => '50g',
                'material' => 'Polycarbonate',
                'tags' => ['sunglasses', 'retro', 'brown'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-2-D1V8gELu.png'],
                'variants' => [['name' => 'Warna', 'options' => ['Brown Tint']]],
            ],
            [
                'id' => '14',
                'name' => 'Wool Beret Hat Mustard',
                'price' => 50000,
                'original_price' => 195000,
                'description' => 'Topi baret bahan wool warna kuning mustard hangat dan fashionable.',
                'condition' => 'Sangat Baik',
                'brand' => 'Unbranded',
                'category' => 'Aksesoris',
                'stock' => 1,
                'weight' => '100g',
                'material' => '100% Wool',
                'tags' => ['hat', 'beret', 'wool'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-3-C2haDO2D.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['All Size']]],
            ],
            [
                'id' => '15',
                'name' => 'Silk Scarf Floral Pattern',
                'price' => 60000,
                'original_price' => 240000,
                'description' => 'Syal sutra lembut dengan corak bunga-bunga pastel yang mewah.',
                'condition' => 'Sangat Baik',
                'brand' => 'Zara',
                'category' => 'Aksesoris',
                'stock' => 1,
                'weight' => '80g',
                'material' => 'Silk Silk',
                'tags' => ['scarf', 'silk', 'floral'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-4-C6tSW0GE.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['Standard']]],
            ],
            [
                'id' => '16',
                'name' => 'Gold Chain Necklace',
                'price' => 70000,
                'original_price' => 290000,
                'description' => 'Kalung rantai warna emas minimalis. Tahan karat dan cocok untuk daily wear.',
                'condition' => 'Sangat Baik',
                'brand' => 'H&M',
                'category' => 'Aksesoris',
                'stock' => 1,
                'weight' => '30g',
                'material' => 'Stainless Steel Gold Plated',
                'tags' => ['necklace', 'gold', 'minimalist'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-5-QEo8_1xu.png'],
                'variants' => [['name' => 'Panjang', 'options' => ['45cm']]],
            ],
            [
                'id' => '17',
                'name' => 'Oversized Flannel Red-Navy',
                'price' => 95000,
                'original_price' => 380000,
                'description' => 'Kemeja flanel kotak-kotak merah navy oversize. Bahan tebal hangat.',
                'condition' => 'Baik',
                'brand' => 'Uniqlo',
                'category' => 'Fashion Pria',
                'stock' => 1,
                'weight' => '350g',
                'material' => 'Flannel Cotton',
                'tags' => ['flannel', 'shirt', 'red'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-2-D1V8gELu.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['L', 'XL']]],
            ],
            [
                'id' => '18',
                'name' => 'Leather Loafers Classic',
                'price' => 250000,
                'original_price' => 1100000,
                'description' => 'Sepatu loafers kulit warna hitam. Cocok untuk ngantor atau hangout formal.',
                'condition' => 'Sangat Baik',
                'brand' => 'Pedro',
                'category' => 'Sepatu',
                'stock' => 1,
                'weight' => '800g',
                'material' => 'Genuine Leather',
                'tags' => ['loafers', 'leather', 'black'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-3-C2haDO2D.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['41', '42']]],
            ],
            [
                'id' => '19',
                'name' => 'Tote Bag Canvas Aesthetic',
                'price' => 35000,
                'original_price' => 120000,
                'description' => 'Tote bag kanvas tebal dengan sablon estetik minimalis. Cocok untuk kuliah.',
                'condition' => 'Sangat Baik',
                'brand' => 'Unbranded',
                'category' => 'Tas',
                'stock' => 1,
                'weight' => '150g',
                'material' => 'Canvas Premium',
                'tags' => ['totebag', 'canvas', 'aesthetic'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-4-C6tSW0GE.png'],
                'variants' => [['name' => 'Ukuran', 'options' => ['35x40cm']]],
            ],
            [
                'id' => '20',
                'name' => 'Vintage Watch Gold Strap',
                'price' => 350000,
                'original_price' => 1500000,
                'description' => 'Jam tangan vintage dengan strap rantai lapis emas. Mewah dan berfungsi normal.',
                'condition' => 'Sangat Baik',
                'brand' => 'Casio',
                'category' => 'Aksesoris',
                'stock' => 1,
                'weight' => '120g',
                'material' => 'Stainless Steel',
                'tags' => ['watch', 'vintage', 'gold'],
                'status' => 'published',
                'shopee_link' => 'https://shopee.co.id/',
                'photos' => ['./assets/image-5-QEo8_1xu.png'],
                'variants' => [['name' => 'Warna', 'options' => ['Gold']]],
            ],
        ];

        foreach ($products as $p) {
            Product::updateOrCreate(['id' => $p['id']], $p);
        }
    }
}
